### ISSUE TITLE
What's the value of M in equation 14?

### ISSUE THREAD

**Issue by zeal-up** [YutingZhang/lmdis-rep#4]
Hi, professor Zhang!
Equation 14 in your paper:
![image](https://user-images.githubusercontent.com/40826585/44710213-2a10b600-aade-11e8-924f-a022d92b6125.png)
However, I can't find the value of 'M' in Appendix nor in the main paper. Also, there seems to be no mention in the paper about the chosen of the Gassion variance in decoder. 
![image](https://user-images.githubusercontent.com/40826585/44710707-5547d500-aadf-11e8-9851-a3fe7b0d9931.png)
 I think these two are hyperparameters?

**Comment by YutingZhang** [comment]
They are specified here:

https://github.com/YutingZhang/lmdis-rep/blob/aa5cabc6ec93c202ffd2c098440aa947480f8e3d/exp-ae-aflw-10.py#L52-L53

The largest \sigma_{dec} is 1/8. They each time I scale it by keypoint_decoding_heatmap_level_base for keypoint_decoding_heatmap_levels times, i.e., 
1/(2^3), 1/(2^3.5), 1/(2^4), 1/(2^4.5), 1/(2^5)
